branch-defaults:
  elastic-beanstalk-poc:
    environment: null
    group_suffix: null
global:
  application_name: nginx-poc-node
  branch: elastic-beanstalk-poc
  default_ec2_keyname: ecspem.pem
  default_platform: ECS running on 64bit Amazon Linux 2
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application
